version: '3'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/1  # Replace YOUR_PASSWORD with a secure password
    ports:
      - 7474:7474  # Neo4j browser
      - 7687:7687  # Bolt protocol for Neo4j drivers
